journal/urls.py
"""
Release: 0.2.2
Author: Golikov Ivan
Date: 10.07.2017
"""

from django.conf.urls import url

from . import views

app_name = 'journal'
urlpatterns = [
    url(r'^pbx/(?P<pbx>\d+)/page-(?P<page>\d+)$', views.pbx_ports_view, name='pbx_ports'),
    url(r'^subscriber_card/(?P<card>\d+)$', views.subscriber_card_view, name='subscriber_card'),
    url(r'^search$', views.search, name='search'),
]

common/views.py
"""
Release: 0.2.2
Author: Golikov Ivan
Date: 10.07.2017
"""

from django.views.generic.list import ListView

from journal.models import PBX


class IndexView(ListView):
    template_name = 'common/index.html'
    context_object_name = 'pbx_list'

    model = PBX

common/templates/common/base.html
{% comment %}
  Release: 0.2.2
  Authors: Golikov Ivan, Asaturan Kristina
  Date: 10.07.2017
{% endcomment %}

<!DOCTYPE html>
<html class="no-js" lang="ru" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title%}{% endblock %}</title>

  {% block css %}
    {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'common/css/foundation.min.css' %}">
      <link rel="stylesheet" href="{% static 'common/css/app.css' %}">
  {% endblock%}
</head>
<body>
   <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu">
        <li class="menu-text">Кроссовые журналы</li>
        <li><a href="{% url 'index' %}">АТС</a></li>

        {% if request.user.is_staff %}
          <li><a href="{% url 'admin:index' %}">Администрирование</a></li>
        {% endif %}
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li>
          <form action="{% url 'journal:search' %}" method="get">
            <div class="input-group top-bar-search">
              <input name="search_input" type="search" placeholder="Поиск…" class="input-group-field" >
              <div class="input-group-button">
                <input type="submit" class="button" value="Искать">
              </div>
            </div>
          </form>
        </li>
        <li style="padding-left: 20px">
          {% if request.user.is_authenticated %}
            Вы вошли как {{ request.user.last_name }} {{ request.user.first_name }}
          {% else %}
            <a href="/admin/login/?next={{ request.path }} ">Войти</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>

    <div class="row content-row">
      <div class="small-1 column"></div>
      <div class="small-11 column">
        {% block page %}{% endblock %}
      </div>
    </div>

  {% block js %}
    <script src="{% static 'common/js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'common/js/vendor/what-input.js' %}"></script>
    <script src="{% static 'common/js/vendor/foundation.min.js' %}"></script>
    <script src="{% static 'common/js/app.js' %}"></script>
  {% endblock js %}
</body>
</html>

common/templates/common/error_page.html
{% extends "common/base.html" %}

{% comment %}
  Release: 0.2.2
  Author: Golikov Ivan
  Date: 10.07.2017
{% endcomment %}

{% block page %}
  <h1>
    {% block error-message %}
    {% endblock error-message %}
  </h1>

  <p>
    {% block help-text %}
    {% endblock help-text %}
  </p>

  {% block return %}
    <p><a href="javascript:history.back()">← Вернуться назад</a></p>
  {% endblock return %}
{% endblock page %}

common/templates/common/index.html
{% extends "common/base.html" %}

{% comment %}
  Release: 0.2.2
  Author: Golikov Ivan
  Date: 10.07.2017
{% endcomment %}

{% load journal_extras %}

{% block title%}
  Главная страница
{% endblock %}

{% block page %}
  <div class="row">
    <div class="small-6 column">
      <h3>АТС предприятия</h3>
      {% for pbx in pbx_list %}
        <p><a href="{% url 'journal:pbx_ports' pbx.pk 1 %}">{{ pbx }}</a></p>
      {% endfor %}
    </div>
    <div class="small-6 column">
      <h3>Последние изменения</h3>
      {% recent_changes 10 %}
    </div>
  </div>
{% endblock%}